version: '3'

services:
  server:
    image: server
    container_name: server-container
    ports:
      - "80:80"
      - "443:443"
    networks:
      - spotify_network
    depends_on:
      - dns
      - router
      - db
      - server1
      - server2
    command: [ "./server.sh" ]

  client:
    image: client
    container_name: client-container
    networks:
      - spotify_network
    command: [ "./client.sh" ]

  dns:
    image: dns
    container_name: dns-container
    networks:
      - spotify_network

  router:
    image: router-image
    container_name: router-container
    networks:
      - spotify_network

  db:
    # puse la bd pero no se si haga falta
    image: db-image
    container_name: db-container
    networks:
      - spotify_network

  server1:
    # no sé si haga falta estos pero por si acaso hago uno más
    image: server
    container_name: server1-container
    networks:
      - spotify_network

networks:
  spotify_network:
